source "https://rubygems.org"


gem "sinatra"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "redis"
gem "hiredis"
gem "unicorn"

group :development do
  gem "rack-mini-profiler", require: false
  gem "rerun", require: false
end
