source "https://rubygems.org"


gem "sinatra"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "unicorn", require: false

group :development do
  gem "rack-mini-profiler"
  gem "rerun", require: false
end
